export const languages = [
  {
    code: 'ar',
    name: 'العربية',
    flag: '🇸🇦',
    link: 'https://youtube.com/playlist?list=PLpk7CtzfzpbJ5u3WkdETU72cxc-UlJJVS&feature=shared',
    progress: 80,
    description: 'ابدأ رحلتك في تعلم اللغة العربية.',
  },
  {
    code: 'en',
    name: 'English',
    flag: '🇺🇸',
    link: 'https://youtube.com/playlist?list=PLAie3YzOYRmley8mMYy1s9XuZYVxW1Ot7&feature=shared',
    progress: 50,
    description: 'Start your journey in learning English.',
  },
  {
    code: 'zh',
    name: '中文',
    flag: '🇨🇳',
    link: 'https://youtube.com/playlist?list=PL9_fyJVCwp0Qp-1AY3_uQUIeQ2c4C2csg&feature=shared',
    progress: 2,
    description: '开始学习中文之旅。',
  },
  {
    code: 'fr',
    name: 'Français',
    flag: '🇫🇷',
    link: 'https://youtube.com/playlist?list=PLnazreCxpqRlvlt5Pf4qn4bUoua5nU2Im&feature=shared',
    progress: 1,
    description: 'Commencez votre apprentissage du français.',
  },
  {
    code: 'ja',
    name: '日本語',
    flag: '🇯🇵',
    link: 'https://youtu.be/8YV8KmfBbBM?feature=shared',
    progress: 1,
    description: '日本語の学習を始めましょう。',
  },
  {
    code: 'es',
    name: 'Español',
    flag: '🇪🇸',
    link: 'https://youtube.com/playlist?list=PLv63dFTP4Sjq6knRsZQI-bTnRE38cZZoy&feature=shared',
    progress: 1,
    description: 'Comienza tu aprendizaje del español.',
  },
  {
    code: 'hi',
    name: 'हिन्दी',
    flag: '🇮🇳',
    link: 'https://youtu.be/1lrz11BbqCA?feature=shared',
    progress: 1,
    description: 'हिन्दी सीखना शुरू करें।',
  },
  {
    code: 'tr',
    name: 'Türkçe',
    flag: '🇹🇷',
    link: 'https://youtube.com/playlist?list=PLOBMFka6Ca0dlMDOoPJ7ZAwZv_hfo1AKf&feature=shared',
    progress: 1,
    description: 'Türkçe öğrenmeye başlayın.',
  },
  {
    code: 'de',
    name: 'Deutsch',
    flag: '🇩🇪',
    link: 'https://youtube.com/playlist?list=PLk1fjOl39-50kWobutO8NVFzbw9PHtbbg&feature=shared',
    progress: 1,
    description: 'Beginnen Sie mit dem Deutschlernen.',
  },
  {
    code: 'ru',
    name: 'Русский',
    flag: '🇷🇺',
    link: 'https://youtube.com/playlist?list=PLx1Hrg5Bg3xrnm30dNPZ5q2R9J6Zz2vUq&feature=shared',
    progress: 1,
    description: 'Начните изучение русского языка.',
  },
];
