export const languages = [
  {
    code: 'ar',
    name: 'العربية',
    flag: '🇸🇦',
    link: '/Languag/Arabic',
    progress: 80,
    description: 'ابدأ رحلتك في تعلم اللغة العربية.',
  },
  {
    code: 'en',
    name: 'English',
    flag: '🇺🇸',
    link: '/Languag/English',
    progress: 50,
    description: 'Start your journey in learning English.',
  },
  {
    code: 'zh',
    name: '中文',
    flag: '🇨🇳',
    link: '/Languag/Chinese',
    progress: 2,
    description: '开始学习中文之旅。',
  },
  {
    code: 'fr',
    name: 'Français',
    flag: '🇫🇷',
    link: '/Languag/French',
    progress: 1,
    description: 'Commencez votre apprentissage du français.',
  },
  {
    code: 'ja',
    name: '日本語',
    flag: '🇯🇵',
    link: '/Languag/Japanese',
    progress: 1,
    description: '日本語の学習を始めましょう。',
  },
  {
    code: 'es',
    name: 'Español',
    flag: '🇪🇸',
    link: '/Languag/Spanish',
    progress: 1,
    description: 'Comienza tu aprendizaje del español.',
  },
  {
    code: 'hi',
    name: 'हिन्दी',
    flag: '🇮🇳',
    link: '/Languag/Hindi',
    progress: 1,
    description: 'हिन्दी सीखना शुरू करें।',
  },
  {
    code: 'tr',
    name: 'Türkçe',
    flag: '🇹🇷',
    link: '/Languag/Turkish',
    progress: 1,
    description: 'Türkçe öğrenmeye başlayın.',
  },
  {
    code: 'de',
    name: 'Deutsch',
    flag: '🇩🇪',
    link: '/Languag/German',
    progress: 1,
    description: 'Beginnen Sie mit dem Deutschlernen.',
  },
  {
    code: 'ru',
    name: 'Русский',
    flag: '🇷🇺',
    link: '/Languag/Russian',
    progress: 1,
    description: 'Начните изучение русского языка.',
  },
];
